//
// Created by Ruslan Gabdullin on 25.10.2025.
//

#ifndef TONLIB_MULTICLIENT_GETBLOCKTRANSACTIONSEXTHANDLER_H
#define TONLIB_MULTICLIENT_GETBLOCKTRANSACTIONSEXTHANDLER_H


class GetBlockTransactionsExtHandler {};


#endif  // TONLIB_MULTICLIENT_GETBLOCKTRANSACTIONSEXTHANDLER_H
