//
// Created by Ruslan Gabdullin on 25.10.2025.
//

#ifndef TONLIB_MULTICLIENT_GETBLOCKTRANSACTIONSHANDLER_H
#define TONLIB_MULTICLIENT_GETBLOCKTRANSACTIONSHANDLER_H


class GetBlockTransactionsHandler {};


#endif  // TONLIB_MULTICLIENT_GETBLOCKTRANSACTIONSHANDLER_H
