//
// Created by Ruslan Gabdullin on 26.10.2025.
//

#ifndef TONLIB_MULTICLIENT_GETTRANSACTIONSSTDHANDLER_H
#define TONLIB_MULTICLIENT_GETTRANSACTIONSSTDHANDLER_H


class GetTransactionsStdHandler {};


#endif  // TONLIB_MULTICLIENT_GETTRANSACTIONSSTDHANDLER_H
