//
// Created by Ruslan Gabdullin on 25.10.2025.
//

#ifndef TONLIB_MULTICLIENT_GETOUTMSGQUEUESIZEHANDLER_H
#define TONLIB_MULTICLIENT_GETOUTMSGQUEUESIZEHANDLER_H


class GetOutMsgQueueSizeHandler {};


#endif  // TONLIB_MULTICLIENT_GETOUTMSGQUEUESIZEHANDLER_H
