//
// Created by Ruslan Gabdullin on 25.10.2025.
//

#ifndef TONLIB_MULTICLIENT_GETSHARDSHANDLER_H
#define TONLIB_MULTICLIENT_GETSHARDSHANDLER_H


class GetShardsHandler {};


#endif  // TONLIB_MULTICLIENT_GETSHARDSHANDLER_H
