//
// Created by Ruslan Gabdullin on 17.10.2025.
//

#ifndef TONLIB_MULTICLIENT_GETADDRESSBALANCEHANDLER_H
#define TONLIB_MULTICLIENT_GETADDRESSBALANCEHANDLER_H

#endif  // TONLIB_MULTICLIENT_GETADDRESSBALANCEHANDLER_H
